# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: "3.4"

services:
  catalogdb:
    image: postgres
    container_name: catalogdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=CatalogDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data

  catalogapi:
    image: catalogapi
    build:
      context: .
      dockerfile: src/Catalog/Catalog.API/Dockerfile
    ports:
      - 6000:8080
      - 6060:8081
    depends_on:
      - catalogdb
    environment:
      - ConnectionStrings__DefaultConnection=Host=catalogdb;Port=5432;Database=CatalogDb;Username=admin;Password=admin1234

  basketdb:
    image: postgres
    container_name: basketdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=BasketDb
    ports:
      - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data

  distributedcache:
    image: redis
    container_name: distributedcache
    ports:
      - "6379:6379"

  basketapi:
    image: basketapi
    build:
      context: .
      dockerfile: src/Basket/Basket.API/Dockerfile
    ports:
      - 6001:8080
      - 6061:8081
    depends_on:
      - basketdb
      - distributedcache
      - discountgrpc
    environment:
      - ConnectionStrings__DefaultConnection=Host=basketdb;Port=5432;Database=BasketDb;Username=admin;Password=admin1234
      - ConnectionStrings__RedisConnection=distributedcache:6379
      - GrpcSettings__DiscountUri=https://discount.grpc:8081

  discountgrpc:
    image: discountgrpc
    build:
      context: .
      dockerfile: src/Discount/DiscountGrpc/Dockerfile
    ports:
      - 6002:8080
      - 6062:8081
    volumes:
      - discountdata:/app/data
      - ${HOME}/.aspnet/https:/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Data Source=/app/data/discountdb.sqlite
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=admin1234
volumes:
  postgres_catalog:
  postgres_basket:
  discountdata:
