# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: "3.4"

services:
  catalogapi:
    image: catalogapi
    build:
      context: .
      dockerfile: src/Catalog/Catalog.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 6000:8080
      - 6060:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  basketapi:
    image: basketapi
    build:
      context: .
      dockerfile: src/Basket/Basket.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 6001:8080
      - 6061:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
