# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: "3.4"

services:
  catalogdb:
    image: postgres
    container_name: catalogdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=CatalogDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data

  catalogapi:
    image: catalogapi
    build:
      context: .
      dockerfile: src/Catalog/Catalog.API/Dockerfile
    ports:
      - 6000:8080
      - 6060:8081
    depends_on:
      - catalogdb
    environment:
      - ConnectionStrings__DefaultConnection=Host=catalogdb;Port=5432;Database=CatalogDb;Username=admin;Password=admin1234

  basketdb:
    image: postgres
    container_name: basketdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=BasketDb
    ports:
      - "5433:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data

  # basketapi:
  #   image: basketapi
  #   build:
  #     context: .
  #     dockerfile: src/Basket/Basket.API/Dockerfile
  #   ports:
  #     - 6000:8080
  #     - 6060:8081
  #   depends_on:
  #     - basketdb
  #   environment:
  #     - ConnectionStrings__DefaultConnection=Host=basketdb;Port=5432;Database=BasketDb;Username=admin;Password=admin1234

volumes:
  postgres_catalog:
  postgres_basket:
